name: CI/CD

on:
  push:
    branches: [main]
    tags:
      - v**
  pull_request:
    branches: [main]

jobs:
  clippy_check:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: kristof-mattei/clippy-check@pr-for-original-repo # switch to original when merged https://github.com/actions-rs/clippy-check/pull/165
        with:
          args: --all-features -- -D warnings

  fmt_check:
    name: Format (fmt)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - name: Rustfmt
        run: cargo fmt --all-features -- --check

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --all-features  --verbose
      - name: Tests
        run: cargo test --all-features --verbose

  coverage_report:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: llvm-tools-preview
          override: true
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: "./lcov.info"
          github-token: ${{ secrets.GITHUB_TOKEN }}
