name: Pages

on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  pages:
    name: Publish pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Docs
        run: cargo doc --no-deps
      - name: Run Benchmark
        run: cargo bench
      - name: Build Pages
        run: |
          mkdir pages
          cp -R target/doc/* pages
          cp -R target/criterion pages/benchmark
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
