name: Publish

on:
  push:
    tags:
      - v**

jobs:
  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment:
      name: crates.io
      url: https://crates.io/crates/graph-algo-ptas

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
